name: PingMySlack

on:
  push:
    branches: [ "master" ]

permissions:
  contents: write

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Validate Composer
      run: |
        composer validate --strict

    - name: Install Composer
      run: |
        composer install --prefer-dist --no-progress

    - name: Run Linting
      run: |
        composer run lint

    - name: Run Testing
      run: |
        composer run test

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: ci
    steps:
    - uses: actions/checkout@v3

    - name: Checkout to Master Built branch
      if: github.ref == 'refs/heads/master'
      env:
        USER_EMAIL: "badasswpdev@gmail.com"
        USER_NAME: "badasswp"
      run: |
        git config user.email "${USER_EMAIL}"
        git config user.name "${USER_NAME}"
        git checkout -b master-built

    - name: Build Vendor folder
      run: |
        composer install --no-dev
        git add vendor/ -f
        git rm composer.json

    - name: Clean Up Files
      run: |
        while IFS= read -r file; do
          git rm -rf "$file"
        done < .deployignore
        git rm .deployignore
        git clean -f composer.lock

    - name: Push to Master Built
      run: |
        git commit -m "push to master-built"
        git push origin master-built -f
        rm -rf .git
